# Generated by Django 4.2.24 on 2025-10-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram')], default='kg', max_length=2)),
                ('height', models.FloatField()),
                ('height_unit', models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter')], default='cm', max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
