# Generated by Django 4.2.24 on 2025-10-16 21:09

from django.db import migrations, models
import person.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13, validators=[person.validators.validate_phone])),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(help_text='Informe o CPF com ou sem pontuação.', max_length=11, unique=True, validators=[person.validators.validate_cpf])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
