# Generated by Django 4.2.24 on 2025-10-22 20:04

from django.db import migrations, models
import person.validators


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.CharField(help_text='Enter the CPF with or without punctuation.', max_length=11, unique=True, validators=[person.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[person.validators.validate_phone]),
        ),
    ]
