# Generated by Django 4.2.24 on 2025-10-16 21:09

from django.db import migrations, models
import django.db.models.deletion
import vets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('crmv', models.CharField(help_text='Informe no formato UF12345 (ex.: MG12345)', max_length=8, unique=True, validators=[vets.validators.validate_crmv])),
                ('specialty', models.CharField(max_length=100)),
            ],
            bases=('person.person',),
        ),
    ]
