# Generated by Django 4.2.24 on 2025-10-22 20:04

from django.db import migrations, models
import vets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='crmv',
            field=models.CharField(help_text='Enter in the format UF12345 (e.g., MG12345)', max_length=8, unique=True, validators=[vets.validators.validate_crmv]),
        ),
    ]
